### ISSUE TITLE
upate reflection

### ISSUE THREAD

**Issue by andrealee011** [UBC-MDS/DSCI-532_gr202_r_dashboard#43]

**Comment by zanderhinton** [comment]
Update reflection with links to issues:
- The following line: ""In order to improve the speed of our app, we've decided to use a smaller dataset which only incorporates the data associated with the top ten most commited crimes. This significantly reduced our overhead and our app can load much quicker than before."  can be linked to any number of the peer feedback issues, for instance(https://github.com/UBC-MDS/DSCI-532_gr202_dashboard/issues/53) :   

The following section has to be adjusted,  did not do modularization in R

- App Maintenance and Refactoring
We have done significant refactoring of our code. The app file structure has been reorganized, by abstracting function definitions out of our app.py file to a new separate functions.py helper file. Code hygiene has also been improved by adding detailed docstrings for all functions, and making our code 'Pythonic' when possible (for example, dictionary comprehensions for long dropdown menus
